src/Entity/Imagenes.php
<?php

namespace App\Entity;

use App\Repository\ImagenesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ImagenesRepository::class)
 */
class Imagenes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $descripcion;

    /**
     * @ORM\Column(type="integer")
     */
    private $num_visualizaciones;

    /**
     * @ORM\Column(type="integer")
     */
    private $num_likes;

    /**
     * @ORM\Column(type="integer")
     */
    private $num_descargas;

    /**
     * @ORM\ManyToOne(targetEntity=Categorias::class, inversedBy="imagenes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categoria;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(string $descripcion): self
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getNumVisualizaciones(): ?int
    {
        return $this->num_visualizaciones;
    }

    public function setNumVisualizaciones(int $num_visualizaciones): self
    {
        $this->num_visualizaciones = $num_visualizaciones;

        return $this;
    }

    public function getNumLikes(): ?int
    {
        return $this->num_likes;
    }

    public function setNumLikes(int $num_likes): self
    {
        $this->num_likes = $num_likes;

        return $this;
    }

    public function getNumDescargas(): ?int
    {
        return $this->num_descargas;
    }

    public function setNumDescargas(int $num_descargas): self
    {
        $this->num_descargas = $num_descargas;

        return $this;
    }

    public function getCategoria(): ?Categorias
    {
        return $this->categoria;
    }

    public function setCategoria(?Categorias $categoria): self
    {
        $this->categoria = $categoria;

        return $this;
    }
}

src/Controller/GaleriaController.php
<?php

namespace App\Controller;

use App\Entity\Imagenes;
use App\Form\ImagenesType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\String\Slugger\SluggerInterface;

class GaleriaController extends AbstractController
{
    #[Route('/galeria', name: 'galeria')]
    public function index(Request $request,SluggerInterface $slugger): Response
    {
        $imagenes = new Imagenes();
        $form = $this->createForm(ImagenesType::class,$imagenes);
        $form->handleRequest($request);

        $entityManager = $this->getDoctrine()->getManager();

        $arrayImagenes = $entityManager->getRepository(Imagenes::class)->findAll();


        if(($form->isSubmitted()) && ($form->isValid())) {

            //Ponemos por defecto los valores de los likes,descargas y visualizaciones
            $imagenes->setNumDescargas(0);
            $imagenes->setNumLikes(0);
            $imagenes->setNumVisualizaciones(0);

            $imageFile = $form->get('nombre')->getData();
            if($imageFile){
                $originalFilename = pathinfo($imageFile->getClientOriginalName(),PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$imageFile->guessExtension();

                // Move the file to the directory where photos are stored
                try {
                    $imageFile->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    throw new \Exception('Error al subir la imagen');
                }
                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $imagenes->setNombre($newFilename);
            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($imagenes);

            $entityManager->flush();
            $this->addFlash("exito", "Imagen subida con exito");
            return $this->redirectToRoute('galeria');
        }
        return $this->render('galeria/index.html.twig', [
            'controller_name' => 'GaleriaController',
            'formulario' => $form->createView(),
            'imagenes' => $arrayImagenes
        ]);
    }
}

templates/galeria/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello GaleriaController!{% endblock %}

{% block body %}
{{ parent() }}
    <div id="galeria">
        <div class="container">
            <div class="col-xs-12 col-sm-8 col-sm-push-2">
                <h1>GALERIA</h1>
                <hr>
                {{ form(formulario) }}
        <hr class="divider">
        <div class="imagenes_galeria">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Imagen</th>
                    <th scope="col">Categoria</th>
                    <th scope="col">Descripcion</th>
                    <th scope="col">Visualizaciones</th>
                    <th scope="col">Likes</th>
                    <th scope="col">Descargas</th>
                </tr>
                </thead>
                <tbody>
                {% for i in imagenes %}
                <tr>
                    <th scope="row">{{ i.id }}</th>
                    <td>
                        <img width="100px" src="{{ asset('uploads/'~i.nombre) }}">
                    </td>
                    <td>{{ i.categoria }} </td>
                    <td>{{ i.descripcion }}</td>
                    <td>{{ i.numVisualizaciones }}</td>
                    <td>{{ i.numLikes }}</td>
                    <td>{{ i.numDescargas }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <hr class="divider">
        <hr class="divider">
        <div class="address">
            <h3>GET IN TOUCH</h3>
            <hr>
            <p>Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero.</p>
            <div class="ending text-center">
                <ul class="list-inline social-buttons">
                    <li><a href="#"><i class="fa fa-facebook sr-icons"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-twitter sr-icons"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-google-plus sr-icons"></i></a>
                    </li>
                </ul>
                <? require 'partials/asociados.part.php' ?>
                <ul class="list-inline contact">
                    <li class="footer-number"><i class="fa fa-phone sr-icons"></i>  (00228)92229954 </li>
                    <li><i class="fa fa-envelope sr-icons"></i>  kouvenceslas93@gmail.com</li>
                </ul>
                <p>Photography Fanatic Template &copy; 2017</p>
            </div>
        </div>
    </div>
{% endblock %}